//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int ResumeId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
    }
}
