//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.WorkingWithObjectServices.Recipe8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int EmployeeNumber { get; set; }
        public string Name { get; set; }
        public decimal Salary { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
