//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Ingredient_Recipe", "Recipe", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomEFRecipe6.Recipe), "Ingredient", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomEFRecipe6.Ingredient), true)]
[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Step_Recipe", "Recipe", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomEFRecipe6.Recipe), "Step", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomEFRecipe6.Step), true)]

#endregion

namespace CustomEFRecipe6
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Step> Steps
        {
            get
            {
                if ((_Steps == null))
                {
                    _Steps = base.CreateObjectSet<Step>("Steps");
                }
                return _Steps;
            }
        }
        private ObjectSet<Step> _Steps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Steps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSteps(Step step)
        {
            base.AddObject("Steps", step);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientId, global::System.String name, global::System.Int32 recipeId)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientId = ingredientId;
            ingredient.Name = name;
            ingredient.RecipeId = recipeId;
            return ingredient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                OnRecipeIdChanging(value);
                ReportPropertyChanging("RecipeId");
                _RecipeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeId");
                OnRecipeIdChanged();
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Ingredient_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Ingredient_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Ingredient_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Ingredient_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("EFRecipesModel.FK_Ingredient_Recipe", "Recipe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="recipeName">Initial value of the RecipeName property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeId, global::System.String recipeName)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeId = recipeId;
            recipe.RecipeName = recipeName;
            return recipe;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecipeName
        {
            get
            {
                return _RecipeName;
            }
            set
            {
                OnRecipeNameChanging(value);
                ReportPropertyChanging("RecipeName");
                _RecipeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecipeName");
                OnRecipeNameChanged();
            }
        }
        private global::System.String _RecipeName;
        partial void OnRecipeNameChanging(global::System.String value);
        partial void OnRecipeNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Ingredient_Recipe", "Ingredient")]
        public EntityCollection<Ingredient> Ingredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredient>("EFRecipesModel.FK_Ingredient_Recipe", "Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredient>("EFRecipesModel.FK_Ingredient_Recipe", "Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Step_Recipe", "Step")]
        public EntityCollection<Step> Steps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Step>("EFRecipesModel.FK_Step_Recipe", "Step");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Step>("EFRecipesModel.FK_Step_Recipe", "Step", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Step")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Step : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Step object.
        /// </summary>
        /// <param name="stepId">Initial value of the StepId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        public static Step CreateStep(global::System.Int32 stepId, global::System.String description, global::System.Int32 recipeId)
        {
            Step step = new Step();
            step.StepId = stepId;
            step.Description = description;
            step.RecipeId = recipeId;
            return step;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StepId
        {
            get
            {
                return _StepId;
            }
            set
            {
                if (_StepId != value)
                {
                    OnStepIdChanging(value);
                    ReportPropertyChanging("StepId");
                    _StepId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StepId");
                    OnStepIdChanged();
                }
            }
        }
        private global::System.Int32 _StepId;
        partial void OnStepIdChanging(global::System.Int32 value);
        partial void OnStepIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                OnRecipeIdChanging(value);
                ReportPropertyChanging("RecipeId");
                _RecipeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeId");
                OnRecipeIdChanged();
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Step_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Step_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Step_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("EFRecipesModel.FK_Step_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("EFRecipesModel.FK_Step_Recipe", "Recipe", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
