//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Core.Objects;
	using System.Data.Entity.Infrastructure;
	using System.Linq;
    public partial class EFRecipesEntities : DbContext, IReservationContext
    {
        public EFRecipesEntities()
            : base("name=EFRecipesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Reservation> Reservations { get; set; }
        public IDbSet<Schedule> Schedules { get; set; }
        public IDbSet<Train> Trains { get; set; }

		public override int SaveChanges()
		{
			this.ChangeTracker.DetectChanges();
			var entries = from e in this.ChangeTracker.Entries().Where(e => e.State == (System.Data.Entity.EntityState.Added | EntityState.Modified | EntityState.Deleted))
						  where (e.Entity != null) &&
								(e.Entity is IValidate)
						  select e;
			foreach (var entry in entries)
			{
				switch (entry.State)
				{
					case EntityState.Added:
						((IValidate)entry.Entity).Validate(ChangeAction.Insert);
						break;
					case EntityState.Modified:
						((IValidate)entry.Entity).Validate(ChangeAction.Update);
						break;
					case EntityState.Deleted:
						((IValidate)entry.Entity).Validate(ChangeAction.Delete);
						break;
				}
			}
			return base.SaveChanges();
		}

    }
}
