//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int ScheduleId { get; set; }
        public string Passenger { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
	public partial class Reservation : IValidate
	{
		public void Validate(ChangeAction action)
		{
			if (action == ChangeAction.Insert)
			{
				if (Schedule.Reservations.Count(r =>
							  r.ReservationId != ReservationId &&
							  r.Passenger == this.Passenger) > 0)
					throw new InvalidOperationException(
							  "Reservation for the passenger already exists");
			}
		}
	}
}
