//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int TrainId { get; set; }
        public string TrainName { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
