//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe3_14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associate
    {
        public Associate()
        {
            this.AssociateSalaries = new HashSet<AssociateSalary>();
        }
    
        public int AssociateID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AssociateSalary> AssociateSalaries { get; set; }
    }
}
