//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe3_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PostID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
