//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCORecipe44
{
    using System;
    
    public partial class Name
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
