//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.StoredProcedures.Recipe8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Recipe8Context : DbContext
    {
        public Recipe8Context()
            : base("name=Recipe8Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Athlete> Athletes { get; set; }
    
        public virtual int DeleteAthlete(Nullable<int> athleteId)
        {
            var athleteIdParameter = athleteId.HasValue ?
                new ObjectParameter("AthleteId", athleteId) :
                new ObjectParameter("AthleteId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAthlete", athleteIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InsertAthlete(string name, Nullable<int> height, Nullable<int> weight)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var heightParameter = height.HasValue ?
                new ObjectParameter("Height", height) :
                new ObjectParameter("Height", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InsertAthlete", nameParameter, heightParameter, weightParameter);
        }
    
        public virtual int UpdateAthlete(Nullable<int> athleteId, string name, Nullable<int> height, Nullable<int> weight)
        {
            var athleteIdParameter = athleteId.HasValue ?
                new ObjectParameter("AthleteId", athleteId) :
                new ObjectParameter("AthleteId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var heightParameter = height.HasValue ?
                new ObjectParameter("Height", height) :
                new ObjectParameter("Height", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAthlete", athleteIdParameter, nameParameter, heightParameter, weightParameter);
        }
    }
}
