//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associate
    {
        public Associate()
        {
            this.Paychecks = new HashSet<Paycheck>();
        }
    
        public int AssociateId { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Paycheck> Paychecks { get; set; }
    }
}
