//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paycheck
    {
        public int PayCheckId { get; set; }
        public int AssociateId { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal Gross { get; set; }
    
        public virtual Associate Associate { get; set; }
    }
}
