//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe10
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD
    {
        public CD()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int CDId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
