//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public string Title { get; set; }
        public string Artist { get; set; }
        public int CDId { get; set; }
    }
}
