//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe3_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidID { get; set; }
        public int JobID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Bidder { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
