//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe3_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int JobID { get; set; }
        public string JobDetails { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
