//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomEFRecipe12
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int SalesOrderId { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<bool> Shipped { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
