//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionsEFRecipe5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int HotelId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
