//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.ModelingFundamentals.Recipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poet
    {
        public Poet()
        {
            this.Poems = new HashSet<Poem>();
        }
    
        public int PoetId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Poem> Poems { get; set; }
    }
}
