//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionsEFRecipe9
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieRental
    {
        public int RentalId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<decimal> LateFees { get; set; }
    }
}
