//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.BeyondModelingBasics.Recipe9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        public int ToyId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
