//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.BeyondModelingBasics.Recipe11
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Member
    {
        public int MemberId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
