//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.StoredProcedures.Recipe7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Recipe7Context : DbContext
    {
        public Recipe7Context()
            : base("name=Recipe7Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> People { get; set; }
    
        public virtual ObjectResult<Person> GetAllPeople()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Person>("GetAllPeople");
        }
    
        public virtual ObjectResult<Person> GetAllPeople(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Person>("GetAllPeople", mergeOption);
        }
    }
}
