//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomEFRecipe11
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingTicket
    {
        public int TicketId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
