//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomEFRecipe7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public System.Guid PurchaseOrderId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Paid { get; set; }
    }
}
