//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCORecipe77
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using System.Linq;
    public partial class EFRecipesEntities : DbContext
    {
        public EFRecipesEntities()
            : base("name=EFRecipesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Speaker> Speakers { get; set; }
        public DbSet<Talk> Talks { get; set; }

		public override int SaveChanges()
		{
			var changeSet = this.ChangeTracker.Entries().Where(e => e.Entity is Talk);
			if (changeSet != null)
			{
				foreach (var entry in changeSet.Where(c => c.State == System.Data.Entity.EntityState.Added).Select(a => a.Entity as Talk))
				{
					entry.CreateDate = DateTime.UtcNow;
					entry.RevisedDate = DateTime.UtcNow;
				}
				foreach (var entry in changeSet.Where(c => c.State == System.Data.Entity.EntityState.Modified).Select(a => a.Entity as Talk))
				{
					entry.RevisedDate = DateTime.UtcNow;
				}
			}
			return base.SaveChanges();
		}	
	}
}
