//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Recipe6
{
    public partial class Hotel
    {
        public Hotel()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int HotelId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
