//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Recipe6
{
    public partial class Room
    {
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int RoomId { get; set; }
        public decimal Rate { get; set; }
        public int HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
