//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe3_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopSelling
    {
        public int ProductID { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
