//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foreman
    {
        public int ForemanId { get; set; }
        public int LocationId { get; set; }
        public string Name { get; set; }
    
        public virtual JobSite JobSite { get; set; }
    }
}
