//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe6
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSite : Location
    {
        public JobSite()
        {
            this.Foremen = new HashSet<Foreman>();
            this.Plumbers = new HashSet<Plumber>();
        }
    
        public string JobSiteName { get; set; }
    
        public virtual ICollection<Foreman> Foremen { get; set; }
        public virtual ICollection<Plumber> Plumbers { get; set; }
    }
}
