//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int PhoneId { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
    }
}
