//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public Developer()
        {
            this.Apps = new HashSet<App>();
        }
    
        public int DeveloperId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<App> Apps { get; set; }
    }
}
