//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.StoredProcedures.Recipe5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Recipe5Context : DbContext
    {
        public Recipe5Context()
            : base("name=Recipe5Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Member> Members { get; set; }
        public DbSet<Message> Messages { get; set; }
    
        public virtual ObjectResult<Member> MembersWithTheMostMessages(Nullable<System.DateTime> datesent)
        {
            var datesentParameter = datesent.HasValue ?
                new ObjectParameter("datesent", datesent) :
                new ObjectParameter("datesent", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Member>("MembersWithTheMostMessages", datesentParameter);
        }
    
        public virtual ObjectResult<Member> MembersWithTheMostMessages(Nullable<System.DateTime> datesent, MergeOption mergeOption)
        {
            var datesentParameter = datesent.HasValue ?
                new ObjectParameter("datesent", datesent) :
                new ObjectParameter("datesent", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Member>("MembersWithTheMostMessages", mergeOption, datesentParameter);
        }
    }
}
