//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.StoredProcedures.Recipe3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATMMachine
    {
        public ATMMachine()
        {
            this.ATMWithdrawals = new HashSet<ATMWithdrawal>();
        }
    
        public int ATMId { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<ATMWithdrawal> ATMWithdrawals { get; set; }
    }
}
