//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apress.EF6Recipes.StoredProcedures.Recipe3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATMWithdrawal
    {
        public int WithdrawalId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ATMId { get; set; }
    
        public virtual ATMMachine ATMMachine { get; set; }
    }
}
