//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionsEFRecipe7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int SponsorId { get; set; }
        public string Name { get; set; }
        public int SponsorTypeId { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual SponsorType SponsorType { get; set; }
    }
}
