//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionsEFRecipe7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorType
    {
        public SponsorType()
        {
            this.Sponsors = new HashSet<Sponsor>();
        }
    
        public int SponsorTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Sponsor> Sponsors { get; set; }
    }
}
